name: profile-3d
on:
  schedule: [{cron: "0 5 * * 1"}]   # Mondays 05:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Generate 3D contribution SVGs
      - name: Generate 3D contributions
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # built-in, no need to create
          USERNAME: Ram9199                           # set your username here

      # Move renders into a stable folder on main
      - name: Stage renders under metrics-renders/
        run: |
          mkdir -p metrics-renders/profile-3d-contrib
          mv profile-3d-contrib/* metrics-renders/profile-3d-contrib/

      # Commit the files
      - name: Commit renders
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics-renders/profile-3d-contrib || true
          git commit -m "chore(3d): update renders" || echo "no changes"
          git push
