name: generate-snake
on:
  schedule: [{cron: "0 4 * * *"}]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: Ram9199
          outputs: assets/github-snake.svg

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/github-snake.svg
          git commit -m "chore(snake): update" || echo "no changes"
          git push
